//! Render `system/schemas/{domain,type,origin,status}-values.md` from
//! `vault::schema`.
//!
//! The four value docs were hand-written and drifted from the enums they
//! describe (the vault's `type-values.md` listed 15 of `NoteType`'s 25
//! variants). Making them generated closes that gap by construction: the
//! values table is the enum, each row's prose is `description()`, and the
//! surrounding prose is a `const` per file.
//!
//! `frontmatter.md` stays hand-written on purpose - its field tables exist
//! only in that doc and generating them would invent a second schema with no
//! consumer.
//!
//! Precedent: `crate::sweep::render_cold_report_at` plus its checked-in
//! snapshot fixture. Same shape here - the renderers take `generated_at` as a
//! parameter so the snapshot is reproducible.

use std::path::{Path, PathBuf};

use eyre::{Context, Result};
use vault::schema::{Domain, NoteType, Origin, Status};

/// Vault-relative directory the four generated docs live in.
const SCHEMAS_DIR: &str = "system/schemas";

/// The line every generated file carries directly under its heading. Also the
/// string the drift check leans on in spirit: if a human edits one of these,
/// `sb cortex schema --check` says so.
const DO_NOT_EDIT: &str = "Regenerated by `sb cortex schema --render`; do not edit.";

const DOMAIN_RULES: &str = "\
- Notes in `inbox/` do not require a domain. Domain is assigned during triage.
- Daily notes omit the `domain` field entirely. They are structural, not topical. Query them by `type: daily`.
- Entity hub notes in `entities/` omit `domain`, `origin`, and `status` by contract.
- When a note spans two domains, pick the primary one. Tags handle the secondary.
- New domain values are added to `Domain` in `vault/src/schema.rs`; this file and any Bases views follow from there.
";

const TYPE_RULES: &str = "\
- Every note must have exactly one type.
- Type describes form, not content. A YouTube video about football is `type: youtube`, `domain: football`.
- When unsure, use `note` as the default.
- New type values are added to `NoteType` in `vault/src/schema.rs`; update any Bases views that filter by type.
";

/// `origin-values.md` alone carries a prose section between the table and the
/// rules; the distinction it draws is the whole reason the field exists.
const ORIGIN_KEY_DISTINCTION: &str = "\
## The Key Distinction

The line between `assisted` and `generated` is: **who originated the thought?**

- **assisted**: Scott found the video, decided it was worth ingesting, and the LLM did the summarization work. Scott's impetus, machine's hands.
- **generated**: The AI analyzed the vault and produced insights Scott did not ask for specifically. AI's thought, surfaced to Scott for review.
";

const ORIGIN_RULES: &str = "\
- Default to `authored` when creating notes manually.
- The borg pipeline always writes `origin: assisted`.
- AI analysis output (digests, vault reviews, pattern detection) writes `origin: generated`.
- Generated content (digests, reviews) lives in `notes/ai/`.
- When in doubt between assisted and generated, ask: \"Did Scott point at a specific thing and say 'process this'?\" If yes, assisted.
";

const STATUS_RULES: &str = "\
- This field is optional. Omit it entirely rather than setting a default.
- Borg may set `status: unread` on ingested content.
- Daily notes, system notes, entity hubs, and MOCs should not have a status.
- Bases views can filter by status to surface unread content or starred favorites.
";

/// Everything that varies between the four generated files. The values table
/// itself comes from the enum, so a spec carries only prose.
struct DocSpec {
    filename: &'static str,
    title: &'static str,
    intro: &'static str,
    see_also: &'static str,
    /// Optional prose section (with its own `##` heading) between the values
    /// table and the Rules block. Only `origin-values.md` uses it.
    extra: Option<&'static str>,
    rules: &'static str,
    rows: fn() -> Vec<Row>,
}

struct Row {
    value: &'static str,
    description: &'static str,
}

fn domain_rows() -> Vec<Row> {
    Domain::all()
        .iter()
        .map(|d| Row {
            value: d.as_str(),
            description: d.description(),
        })
        .collect()
}

fn type_rows() -> Vec<Row> {
    NoteType::all()
        .iter()
        .map(|t| Row {
            value: t.as_str(),
            description: t.description(),
        })
        .collect()
}

fn origin_rows() -> Vec<Row> {
    Origin::all()
        .iter()
        .map(|o| Row {
            value: o.as_str(),
            description: o.description(),
        })
        .collect()
}

fn status_rows() -> Vec<Row> {
    Status::all()
        .iter()
        .map(|s| Row {
            value: s.as_str(),
            description: s.description(),
        })
        .collect()
}

const SPECS: &[DocSpec] = &[
    DocSpec {
        filename: "domain-values.md",
        title: "Domain Values",
        intro: "Canonical list of allowed values for the `domain` frontmatter field. This field \
                replaces physical folder based organization. Notes live in a flat `notes/` folder \
                and domain provides the conceptual grouping.",
        see_also: "[[frontmatter]], [[type-values]], [[origin-values]], [[status-values]]",
        extra: None,
        rules: DOMAIN_RULES,
        rows: domain_rows,
    },
    DocSpec {
        filename: "type-values.md",
        title: "Type Values",
        intro: "Canonical list of allowed values for the `type` frontmatter field. This field \
                describes what kind of note it is, not what topic it covers (that is `domain`).",
        see_also: "[[frontmatter]], [[domain-values]], [[origin-values]], [[status-values]]",
        extra: None,
        rules: TYPE_RULES,
        rows: type_rows,
    },
    DocSpec {
        filename: "origin-values.md",
        title: "Origin Values",
        intro: "Canonical list of allowed values for the `origin` frontmatter field. This field \
                tracks who originated the content and thinking in a note.",
        see_also: "[[frontmatter]], [[domain-values]], [[type-values]], [[status-values]]",
        extra: Some(ORIGIN_KEY_DISTINCTION),
        rules: ORIGIN_RULES,
        rows: origin_rows,
    },
    DocSpec {
        filename: "status-values.md",
        title: "Status Values",
        intro: "Canonical list of allowed values for the `status` frontmatter field. This field \
                tracks your workflow state for a note. It is optional - omit it entirely when not \
                applicable.",
        see_also: "[[frontmatter]], [[domain-values]], [[type-values]], [[origin-values]]",
        extra: None,
        rules: STATUS_RULES,
        rows: status_rows,
    },
];

/// What `render_all` did (or would do) to one file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    /// On-disk bytes already match the render (modulo `generated-at`).
    Unchanged,
    /// On-disk bytes differ, or the file is missing. `--check` exits 1 on this.
    Drifted,
    /// Was drifted, and `--render` wrote the new bytes.
    Written,
}

#[derive(Debug, Clone)]
pub struct FileStatus {
    /// Vault-relative path, e.g. `system/schemas/domain-values.md`.
    pub path: String,
    pub outcome: Outcome,
}

#[derive(Debug, Clone, Default)]
pub struct RenderReport {
    pub files: Vec<FileStatus>,
}

impl RenderReport {
    /// True when any file still differs from the binary. `sb cortex schema
    /// --check` exits 1 on this; `sb doctor` warns on it.
    pub fn drifted(&self) -> bool {
        self.files.iter().any(|f| f.outcome == Outcome::Drifted)
    }

    /// Vault-relative paths that drifted, for the operator-facing message.
    pub fn drifted_paths(&self) -> Vec<&str> {
        self.files
            .iter()
            .filter(|f| f.outcome == Outcome::Drifted)
            .map(|f| f.path.as_str())
            .collect()
    }
}

/// Render the four value docs and compare them to `<vault_root>/system/schemas/`.
///
/// With `apply` false nothing is written and every difference reports
/// `Drifted`. With `apply` true each drifted file is rewritten atomically and
/// reports `Written`; files that already match are left alone, which is what
/// keeps `generated-at` from churning on every run.
pub fn render_all(vault_root: &Path, apply: bool) -> Result<RenderReport> {
    let now = chrono::Utc::now();
    render_all_at(vault_root, apply, now)
}

/// `render_all` with an explicit `now`, so tests get reproducible bytes.
pub fn render_all_at(vault_root: &Path, apply: bool, now: chrono::DateTime<chrono::Utc>) -> Result<RenderReport> {
    let dir = vault_root.join(SCHEMAS_DIR);
    let mut report = RenderReport::default();

    for spec in SPECS {
        let path = dir.join(spec.filename);
        let rel = format!("{SCHEMAS_DIR}/{}", spec.filename);
        let disk = std::fs::read_to_string(&path).ok();
        let matches = disk.as_deref().is_some_and(|d| matches_render(spec, d));

        let outcome = if matches {
            Outcome::Unchanged
        } else if apply {
            let bytes = render_doc(spec, &stamp(now));
            vault::note::write_atomic(&path, bytes.as_bytes())
                .wrap_err_with(|| format!("failed to write {}", path.display()))?;
            Outcome::Written
        } else {
            Outcome::Drifted
        };

        log::debug!("render_all_at: {rel} -> {outcome:?}");
        report.files.push(FileStatus { path: rel, outcome });
    }

    Ok(report)
}

/// Byte-exact comparison with the volatile field neutralised: re-render using
/// the timestamp the on-disk file already carries, then compare. Every other
/// byte must match. A file with no `generated-at:` line (i.e. the hand-written
/// original) can never match, which is the correct answer.
fn matches_render(spec: &DocSpec, disk: &str) -> bool {
    match disk_generated_at(disk) {
        Some(stamp) => render_doc(spec, &stamp) == disk,
        None => false,
    }
}

/// Pull the `generated-at:` value out of a file's frontmatter. Only the
/// leading frontmatter block is searched, so a `generated-at:` mentioned in
/// the body cannot spoof the comparison.
fn disk_generated_at(disk: &str) -> Option<String> {
    let body = disk.strip_prefix("---\n")?;
    let (frontmatter, _) = body.split_once("\n---\n")?;
    frontmatter
        .lines()
        .find_map(|line| line.strip_prefix("generated-at: "))
        .map(str::to_string)
}

fn stamp(now: chrono::DateTime<chrono::Utc>) -> String {
    now.format("%Y-%m-%dT%H:%M:%SZ").to_string()
}

/// Render one doc. `generated_at` is the only input that is not compiled in,
/// which is exactly why the drift check can neutralise it.
fn render_doc(spec: &DocSpec, generated_at: &str) -> String {
    let date = generated_at.split('T').next().unwrap_or(generated_at);

    let mut out = String::new();
    out.push_str("---\n");
    out.push_str(&format!("title: {}\n", spec.title));
    out.push_str(&format!("date: {date}\n"));
    out.push_str("type: system\n");
    out.push_str("domain: system\n");
    out.push_str("origin: generated\n");
    out.push_str(&format!("generated-at: {generated_at}\n"));
    out.push_str("generator: sb cortex schema\n");
    // Pinned so the file can never surface in `cortex sweep --cold`: it is
    // reference material nobody "reads", and it is machine-owned anyway.
    out.push_str("pinned: true\n");
    out.push_str("tags: [obsidian]\n");
    out.push_str("---\n\n");

    out.push_str(&format!("# {}\n\n", spec.title));
    out.push_str(&format!("{}\n\n", spec.intro));
    out.push_str(&format!("{DO_NOT_EDIT}\n\n"));
    out.push_str(&format!("See also: {}\n\n", spec.see_also));

    out.push_str("## Values\n\n");
    out.push_str("| Value | Description |\n");
    out.push_str("|-------|-------------|\n");
    for row in (spec.rows)() {
        out.push_str(&format!("| {} | {} |\n", row.value, row.description));
    }
    out.push('\n');

    if let Some(extra) = spec.extra {
        out.push_str(extra);
        out.push('\n');
    }

    out.push_str("## Rules\n\n");
    out.push_str(spec.rules);

    out
}

/// The four vault-relative paths this module owns. Used by `sb doctor` for its
/// message and by tests.
pub fn doc_paths() -> Vec<PathBuf> {
    SPECS.iter().map(|s| Path::new(SCHEMAS_DIR).join(s.filename)).collect()
}

#[cfg(test)]
mod tests;
