//! Render `system/schemas/{type,origin,status}-values.md` from
//! `vault::schema`, plus `tag-values.md` from `canonical-tags.yml` (P9).
//!
//! The three enum-backed docs were hand-written and drifted from the enums
//! they describe (the vault's `type-values.md` listed 15 of `NoteType`'s 25
//! variants). Making them generated closes that gap by construction: the
//! values table is the enum, each row's prose is `description()`, and the
//! surrounding prose is a `const` per file.
//!
//! `tag-values.md` is the fourth generated doc and the odd one out: its rows
//! come from data (`canonical-tags.yml`, loaded by the caller and passed in),
//! not a compiled `vault::schema` enum, so it cannot share `DocSpec`'s
//! zero-argument `rows: fn() -> Vec<Row>` and gets its own render function
//! (`render_tag_values_doc`) alongside the `SPECS`-driven ones.
//! A fifth generated doc for the retired single-valued classification field
//! existed prior to the tags-only design; its enum, renderer, and file are
//! gone.
//!
//! `frontmatter.md` stays hand-written on purpose - its field tables exist
//! only in that doc and generating them would invent a second schema with no
//! consumer.
//!
//! Precedent: `crate::sweep::render_cold_report_at` plus its checked-in
//! snapshot fixture. Same shape here - the renderers take `generated_at` as a
//! parameter so the snapshot is reproducible.

use std::path::{Path, PathBuf};

use eyre::{Context, Result};
use vault::schema::{NoteType, Origin, Status};

/// Vault-relative directory the three generated docs live in.
const SCHEMAS_DIR: &str = "system/schemas";

/// The line every generated file carries directly under its heading. Also the
/// string the drift check leans on in spirit: if a human edits one of these,
/// `sb cortex schema --check` says so.
const DO_NOT_EDIT: &str = "Regenerated by `sb cortex schema --render`; do not edit.";

const TYPE_RULES: &str = "\
- Every note must have exactly one type.
- Type describes form, not content. A YouTube video about football is `type: youtube`, tagged `football`.
- When unsure, use `note` as the default.
- New type values are added to `NoteType` in `vault/src/schema.rs`; update any Bases views that filter by type.
";

/// `origin-values.md` alone carries a prose section between the table and the
/// rules; the distinction it draws is the whole reason the field exists.
const ORIGIN_KEY_DISTINCTION: &str = "\
## The Key Distinction

The line between `assisted` and `generated` is: **who originated the thought?**

- **assisted**: Scott found the video, decided it was worth ingesting, and the LLM did the summarization work. Scott's impetus, machine's hands.
- **generated**: The AI analyzed the vault and produced insights Scott did not ask for specifically. AI's thought, surfaced to Scott for review.
";

const ORIGIN_RULES: &str = "\
- Default to `authored` when creating notes manually.
- The borg pipeline always writes `origin: assisted`.
- AI analysis output (digests, vault reviews, pattern detection) writes `origin: generated`.
- Generated content (digests, reviews) lives in `notes/ai/`.
- When in doubt between assisted and generated, ask: \"Did Scott point at a specific thing and say 'process this'?\" If yes, assisted.
";

const STATUS_RULES: &str = "\
- This field is optional. Omit it entirely rather than setting a default.
- Borg may set `status: unread` on ingested content.
- Daily notes, system notes, entity hubs, and MOCs should not have a status.
- Bases views can filter by status to surface unread content or starred favorites.
";

/// Everything that varies between the three generated files. The values table
/// itself comes from the enum, so a spec carries only prose.
struct DocSpec {
    filename: &'static str,
    title: &'static str,
    intro: &'static str,
    see_also: &'static str,
    /// Optional prose section (with its own `##` heading) between the values
    /// table and the Rules block. Only `origin-values.md` uses it.
    extra: Option<&'static str>,
    rules: &'static str,
    rows: fn() -> Vec<Row>,
}

struct Row {
    value: &'static str,
    description: &'static str,
}

fn type_rows() -> Vec<Row> {
    NoteType::all()
        .iter()
        .map(|t| Row {
            value: t.as_str(),
            description: t.description(),
        })
        .collect()
}

fn origin_rows() -> Vec<Row> {
    Origin::all()
        .iter()
        .map(|o| Row {
            value: o.as_str(),
            description: o.description(),
        })
        .collect()
}

fn status_rows() -> Vec<Row> {
    Status::all()
        .iter()
        .map(|s| Row {
            value: s.as_str(),
            description: s.description(),
        })
        .collect()
}

const SPECS: &[DocSpec] = &[
    DocSpec {
        filename: "type-values.md",
        title: "Type Values",
        intro: "Canonical list of allowed values for the `type` frontmatter field. This field \
                describes what kind of note it is, not what topic it covers (that is `tags`).",
        see_also: "[[frontmatter]], [[origin-values]], [[status-values]], [[tag-values]]",
        extra: None,
        rules: TYPE_RULES,
        rows: type_rows,
    },
    DocSpec {
        filename: "origin-values.md",
        title: "Origin Values",
        intro: "Canonical list of allowed values for the `origin` frontmatter field. This field \
                tracks who originated the content and thinking in a note.",
        see_also: "[[frontmatter]], [[type-values]], [[status-values]], [[tag-values]]",
        extra: Some(ORIGIN_KEY_DISTINCTION),
        rules: ORIGIN_RULES,
        rows: origin_rows,
    },
    DocSpec {
        filename: "status-values.md",
        title: "Status Values",
        intro: "Canonical list of allowed values for the `status` frontmatter field. This field \
                tracks your workflow state for a note. It is optional - omit it entirely when not \
                applicable.",
        see_also: "[[frontmatter]], [[type-values]], [[origin-values]], [[tag-values]]",
        extra: None,
        rules: STATUS_RULES,
        rows: status_rows,
    },
];

/// What `render_all` did (or would do) to one file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    /// On-disk bytes already match the render (modulo `generated-at`).
    Unchanged,
    /// On-disk bytes differ, or the file is missing. `--check` exits 1 on this.
    Drifted,
    /// Was drifted, and `--render` wrote the new bytes.
    Written,
}

#[derive(Debug, Clone)]
pub struct FileStatus {
    /// Vault-relative path, e.g. `system/schemas/type-values.md`.
    pub path: String,
    pub outcome: Outcome,
}

/// What `render_all` did (or would do) to a `*-values.md` under
/// `system/schemas/` that no spec owns: a doc a retired schema field left
/// behind, which nothing regenerates and nothing else would ever delete.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StrangerOutcome {
    /// Present on disk, owned by no spec. `--check` exits 1 on this.
    Obsolete,
    /// Was obsolete, and `--render` deleted it.
    Removed,
}

#[derive(Debug, Clone)]
pub struct StrangerStatus {
    /// Vault-relative path, e.g. `system/schemas/<retired>-values.md`.
    pub path: String,
    pub outcome: StrangerOutcome,
}

#[derive(Debug, Clone, Default)]
pub struct RenderReport {
    pub files: Vec<FileStatus>,
    /// Unowned `*-values.md` files found beside the generated docs.
    pub strangers: Vec<StrangerStatus>,
}

impl RenderReport {
    /// True when any file still differs from the binary, or an obsolete doc
    /// is still on disk. `sb cortex schema --check` exits 1 on this; `sb
    /// doctor` warns on it.
    pub fn drifted(&self) -> bool {
        self.files.iter().any(|f| f.outcome == Outcome::Drifted)
            || self.strangers.iter().any(|s| s.outcome == StrangerOutcome::Obsolete)
    }

    /// Vault-relative paths that drifted or are obsolete, for the
    /// operator-facing message.
    pub fn drifted_paths(&self) -> Vec<&str> {
        self.files
            .iter()
            .filter(|f| f.outcome == Outcome::Drifted)
            .map(|f| f.path.as_str())
            .chain(
                self.strangers
                    .iter()
                    .filter(|s| s.outcome == StrangerOutcome::Obsolete)
                    .map(|s| s.path.as_str()),
            )
            .collect()
    }
}

/// Render the four value docs and compare them to `<vault_root>/system/schemas/`.
///
/// With `apply` false nothing is written and every difference reports
/// `Drifted`. With `apply` true each drifted file is rewritten atomically and
/// reports `Written`; files that already match are left alone, which is what
/// keeps `generated-at` from churning on every run.
///
/// `tags` is the caller's already-loaded canonical vocabulary (sorted), used
/// only for `tag-values.md` - this function stays filesystem-free for the
/// vocabulary the same way `schema_info_payload` (oracle, P8) does, so it
/// stays unit-testable with no config or `canonical-tags.yml` on disk.
pub fn render_all(vault_root: &Path, apply: bool, tags: &[String]) -> Result<RenderReport> {
    let now = chrono::Utc::now();
    render_all_at(vault_root, apply, now, tags)
}

/// `render_all` with an explicit `now`, so tests get reproducible bytes.
pub fn render_all_at(
    vault_root: &Path,
    apply: bool,
    now: chrono::DateTime<chrono::Utc>,
    tags: &[String],
) -> Result<RenderReport> {
    let dir = vault_root.join(SCHEMAS_DIR);
    let mut report = RenderReport::default();

    for spec in SPECS {
        let path = dir.join(spec.filename);
        let rel = format!("{SCHEMAS_DIR}/{}", spec.filename);
        let disk = std::fs::read_to_string(&path).ok();
        let matches = disk.as_deref().is_some_and(|d| matches_render(spec, d));

        let outcome = if matches {
            Outcome::Unchanged
        } else if apply {
            let bytes = render_doc(spec, &stamp(now));
            vault::note::write_atomic(&path, bytes.as_bytes())
                .wrap_err_with(|| format!("failed to write {}", path.display()))?;
            Outcome::Written
        } else {
            Outcome::Drifted
        };

        log::debug!("render_all_at: {rel} -> {outcome:?}");
        report.files.push(FileStatus { path: rel, outcome });
    }

    let tag_path = dir.join(TAG_VALUES_FILENAME);
    let tag_rel = format!("{SCHEMAS_DIR}/{TAG_VALUES_FILENAME}");
    let tag_disk = std::fs::read_to_string(&tag_path).ok();
    let tag_matches = tag_disk.as_deref().is_some_and(|d| matches_tag_render(tags, d));

    let tag_outcome = if tag_matches {
        Outcome::Unchanged
    } else if apply {
        let bytes = render_tag_values_doc(tags, &stamp(now));
        vault::note::write_atomic(&tag_path, bytes.as_bytes())
            .wrap_err_with(|| format!("failed to write {}", tag_path.display()))?;
        Outcome::Written
    } else {
        Outcome::Drifted
    };
    log::debug!("render_all_at: {tag_rel} -> {tag_outcome:?}");
    report.files.push(FileStatus {
        path: tag_rel,
        outcome: tag_outcome,
    });

    report.strangers = sweep_strangers(&dir, apply)?;

    Ok(report)
}

/// Every `*-values.md` under the schemas dir that `doc_paths` does not own.
/// Detected by shape, not by name, so a doc for a retired field is found
/// without this module ever naming the field. `--check` reports them;
/// `--render` deletes them (plain `remove_file`: cortex has no recoverable
/// removal helper, and the file is regenerable from git history anyway).
fn sweep_strangers(dir: &Path, apply: bool) -> Result<Vec<StrangerStatus>> {
    log::debug!("schema_docs::sweep_strangers: dir={} apply={apply}", dir.display());
    let owned: Vec<PathBuf> = doc_paths();
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) => return Err(e).wrap_err_with(|| format!("failed to list {}", dir.display())),
    };
    let mut strangers = Vec::new();
    for entry in entries {
        let entry = entry.wrap_err_with(|| format!("failed to list {}", dir.display()))?;
        let Some(name) = entry.file_name().to_str().map(str::to_string) else {
            continue;
        };
        if !name.ends_with("-values.md") || owned.iter().any(|p| p == &Path::new(SCHEMAS_DIR).join(&name)) {
            continue;
        }
        let rel = format!("{SCHEMAS_DIR}/{name}");
        let outcome = if apply {
            std::fs::remove_file(entry.path()).wrap_err_with(|| format!("failed to remove {rel}"))?;
            log::info!("schema_docs: removed obsolete schema doc {rel}");
            StrangerOutcome::Removed
        } else {
            log::warn!("schema_docs: obsolete schema doc {rel} is owned by no spec; --render removes it");
            StrangerOutcome::Obsolete
        };
        strangers.push(StrangerStatus { path: rel, outcome });
    }
    strangers.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(strangers)
}

/// Byte-exact comparison with the volatile field neutralised: re-render using
/// the timestamp the on-disk file already carries, then compare. Every other
/// byte must match. A file with no `generated-at:` line (i.e. the hand-written
/// original) can never match, which is the correct answer.
fn matches_render(spec: &DocSpec, disk: &str) -> bool {
    match disk_generated_at(disk) {
        Some(stamp) => render_doc(spec, &stamp) == disk,
        None => false,
    }
}

/// Pull the `generated-at:` value out of a file's frontmatter. Only the
/// leading frontmatter block is searched, so a `generated-at:` mentioned in
/// the body cannot spoof the comparison.
fn disk_generated_at(disk: &str) -> Option<String> {
    let body = disk.strip_prefix("---\n")?;
    let (frontmatter, _) = body.split_once("\n---\n")?;
    frontmatter
        .lines()
        .find_map(|line| line.strip_prefix("generated-at: "))
        .map(str::to_string)
}

fn stamp(now: chrono::DateTime<chrono::Utc>) -> String {
    now.format("%Y-%m-%dT%H:%M:%SZ").to_string()
}

/// The one tag every generated doc carries, in the block form the
/// `tags.format` lint requires and `frontmatter.md` documents. The inline
/// `[obsidian]` spelling these files used to carry was the lint's own
/// finding against the files it generates.
fn push_tags_block(out: &mut String) {
    out.push_str("tags:\n");
    out.push_str("  - obsidian\n");
}

/// Render one doc. `generated_at` is the only input that is not compiled in,
/// which is exactly why the drift check can neutralise it.
fn render_doc(spec: &DocSpec, generated_at: &str) -> String {
    let date = generated_at.split('T').next().unwrap_or(generated_at);

    let mut out = String::new();
    out.push_str("---\n");
    out.push_str(&format!("title: {}\n", spec.title));
    out.push_str(&format!("date: {date}\n"));
    out.push_str("type: system\n");
    out.push_str("origin: generated\n");
    out.push_str(&format!("generated-at: {generated_at}\n"));
    out.push_str("generator: sb cortex schema\n");
    // Pinned so the file can never surface in `cortex sweep --cold`: it is
    // reference material nobody "reads", and it is machine-owned anyway.
    out.push_str("pinned: true\n");
    push_tags_block(&mut out);
    out.push_str("---\n\n");

    out.push_str(&format!("# {}\n\n", spec.title));
    out.push_str(&format!("{}\n\n", spec.intro));
    out.push_str(&format!("{DO_NOT_EDIT}\n\n"));
    out.push_str(&format!("See also: {}\n\n", spec.see_also));

    out.push_str("## Values\n\n");
    out.push_str("| Value | Description |\n");
    out.push_str("|-------|-------------|\n");
    for row in (spec.rows)() {
        out.push_str(&format!("| {} | {} |\n", row.value, row.description));
    }
    out.push('\n');

    if let Some(extra) = spec.extra {
        out.push_str(extra);
        out.push('\n');
    }

    out.push_str("## Rules\n\n");
    out.push_str(spec.rules);

    out
}

/// Vault-relative filename for the fifth generated doc.
const TAG_VALUES_FILENAME: &str = "tag-values.md";

const TAG_RULES: &str = "\
- Every value here comes from `config/canonical-tags.yml`; nothing else adds or removes a canonical tag.
- A note's tags must be a subset of this list, capped at `max-per-note` (`tags.non-canonical`, `tags.cap`).
- Tag assignment goes through the shared classifier (`distillers::tags`), not free text.
- New tags are added to `config/canonical-tags.yml`; this file follows from there via `sb cortex schema --render`.
";

/// Render `tag-values.md`. Unlike the `SPECS`-driven docs, `tags` is data the
/// caller loaded from `canonical-tags.yml` (`sb cortex schema` and `sb
/// doctor` both resolve it through `config.sweep.canonical_path`), not a
/// compiled enum, so this function takes it as a parameter rather than
/// reading a `rows: fn() -> Vec<Row>`.
fn render_tag_values_doc(tags: &[String], generated_at: &str) -> String {
    let date = generated_at.split('T').next().unwrap_or(generated_at);

    let mut out = String::new();
    out.push_str("---\n");
    out.push_str("title: Tag Values\n");
    out.push_str(&format!("date: {date}\n"));
    out.push_str("type: system\n");
    out.push_str("origin: generated\n");
    out.push_str(&format!("generated-at: {generated_at}\n"));
    out.push_str("generator: sb cortex schema\n");
    out.push_str("pinned: true\n");
    push_tags_block(&mut out);
    out.push_str("---\n\n");

    out.push_str("# Tag Values\n\n");
    out.push_str(
        "Canonical list of allowed values for the `tags` frontmatter field. Every note's tags are \
         drawn from this list, capped at `max-per-note`, and stored as a block list.\n\n",
    );
    out.push_str(&format!("{DO_NOT_EDIT}\n\n"));
    out.push_str("See also: [[frontmatter]], [[type-values]], [[origin-values]], [[status-values]]\n\n");

    out.push_str(&format!("## Values ({})\n\n", tags.len()));
    out.push_str("| Tag |\n");
    out.push_str("|-----|\n");
    for tag in tags {
        out.push_str(&format!("| {tag} |\n"));
    }
    out.push('\n');

    out.push_str("## Rules\n\n");
    out.push_str(TAG_RULES);

    out
}

/// Same neutralise-the-timestamp comparison as `matches_render`, for the
/// data-driven tag doc.
fn matches_tag_render(tags: &[String], disk: &str) -> bool {
    match disk_generated_at(disk) {
        Some(stamp) => render_tag_values_doc(tags, &stamp) == disk,
        None => false,
    }
}

/// The five vault-relative paths this module owns. Used by `sb doctor` for its
/// message and by tests.
pub fn doc_paths() -> Vec<PathBuf> {
    let mut paths: Vec<PathBuf> = SPECS.iter().map(|s| Path::new(SCHEMAS_DIR).join(s.filename)).collect();
    paths.push(Path::new(SCHEMAS_DIR).join(TAG_VALUES_FILENAME));
    paths
}

#[cfg(test)]
mod tests;
