//! Numerical parity test for `CandleBertModel`.
//!
//! Phase 3 of `docs/design/2026-05-17-candle-embedding-backend.md`.
//!
//! Asserts that our Candle-backed `bge-small-en-v1.5` produces vectors
//! within cosine distance 1e-3 of the canonical PyTorch reference output
//! from `sentence-transformers`. The reference fixture is generated by
//! `bin/gen-bge-reference.py` and committed to the repo; if it is
//! absent the test prints a hint and skips rather than failing, so
//! contributors who do not have `sentence-transformers` installed are
//! not blocked.
//!
//! When this test fails, walk the design doc's ordered diagnostic
//! checklist before changing the implementation:
//!
//! 1. Mean pooling instead of CLS (cos_dist ~ 0.3-0.6)
//! 2. Missing L2 normalize (norms differ, cos_dist arbitrary)
//! 3. Attention mask not propagated (~0.05-0.2 drift on padded inputs)
//! 4. Wrong `token_type_ids` shape (~0.01-0.05 drift)
//! 5. hf-hub returned a different revision (cos_dist ~ 1.0)

#![cfg(feature = "vec-candle")]

use serde::Deserialize;
use vault::embedding::{CandleBertModel, EmbeddingModel};

const FIXTURE_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/bge-reference.json",);

#[derive(Debug, Deserialize)]
struct Fixture {
    texts: Vec<String>,
    embeddings: Vec<Vec<f32>>,
}

/// Cosine distance (1 - cosine similarity) between two equal-length
/// vectors. Both inputs are assumed L2-normalized; the model produces
/// unit vectors and the fixture's `normalize_embeddings=True` flag
/// guarantees the reference is normalized too.
fn cosine_distance(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "vector dim mismatch");
    let dot: f32 = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum();
    1.0 - dot
}

#[test]
fn candle_bert_matches_sentence_transformers_reference() {
    let raw = match std::fs::read_to_string(FIXTURE_PATH) {
        Ok(s) => s,
        Err(e) => {
            eprintln!(
                "skipping candle parity test: fixture missing at {FIXTURE_PATH} ({e}). \
                 Regenerate with `pipx run --spec sentence-transformers \
                 python bin/gen-bge-reference.py`."
            );
            return;
        }
    };
    let fixture: Fixture = serde_json::from_str(&raw).expect("parse fixture");
    assert_eq!(
        fixture.texts.len(),
        fixture.embeddings.len(),
        "fixture texts/embeddings length mismatch"
    );

    let model = CandleBertModel::load().expect("load CandleBertModel");
    for (text, expected) in fixture.texts.iter().zip(fixture.embeddings.iter()) {
        let got = model.embed_one(text).expect("embed_one");
        let cos_dist = cosine_distance(&got, expected);
        assert!(
            cos_dist < 1e-3,
            "candle drift on {text:?}: cos_dist={cos_dist:.6} (limit 1e-3)"
        );
    }
}
